sudo: required
dist: trusty
language: node_js
node_js:
  - "6"
  - "5"
  - "4"
# addons:
#   apt:
#     sources:
#       - google-chrome
#     packages:
#       - google-chrome-stable
before_install:
  - npm install -g bower
  # - export DISPLAY=:99.0
  # - sh -e /etc/init.d/xvfb start
  # - sleep 3 # give xvfb some time to start
install:
  - npm install
  - bower install
